//File: src/components/data.js
//this is offline db for the cources details instead of database
import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "/Prod-img1.jpg",
    title: "Advance Software Engineer",
    //star: <AiFillStar className="rating-star" />,
    //reviews: "(153 reviews)",
    //prevPrice: "$300",
    //newPrice:"$50",
    Age: "10 to 17",  
    category: "Term 1", 
  },
  {
    img: "/Prod-img7.jpg",
    title: "Advance Computing Concepts",
    //star: <AiFillStar className="rating-star" />,
    //reviews: "(123 reviews)",
    //prevPrice: "$140,00",
    //newPrice: "$100",
      Age: "6 to 9",
      category: "Term 1",
  },

//   {
//         img: "/Prod-img3.jpg",
//       title: "Robo traveler",
//         star: <AiFillStar className="rating-star" />,
//         reviews: "(123 reviews)",
//         //prevPrice: "$140,00",
//         newPrice: "$150",
//       Age: "6 to 9",
//       category: "Term 1",
//     },
//     {
//         img: "/Prod-img4.jpg",
//         title: "Robo Scientist",
//         star: <AiFillStar className="rating-star" />,
//         reviews: "(123 reviews)",
//         //prevPrice: "$140,00",
//         newPrice: "$50",
//         Age: "6 to 9",
//         category: "Term 1",
//     },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Early Simple Machines L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "6 to 9",
    //     category: " ",
    // },
    {
        img: "/Prod-img6.jpg",
        title: "Advance System Programming",
        //star: <AiFillStar className="rating-star" />,
        //reviews: "(123 reviews)",
        //prevPrice: "$140,00",
        //newPrice: "$150",
        Age: "10 to 17",
        category: "Term 2",
    },
    {
        img: "/Prod-img5.jpg",
        title: "Advance Database Topics",
        //star: <AiFillStar className="rating-star" />,
        //reviews: "(123 reviews)",
        //prevPrice: "$140,00",
        //newPrice: "$50",
        Age: "6 to 9",
        category: "Term 2",
    },
    {
        img: "/Prod-img4.jpg",
        title: "Internet Application Dist. System",
        //star: <AiFillStar className="rating-star" />,
        //reviews: "(123 reviews)",
        //prevPrice: "$140,00",
        //newPrice: "$100",
        Age: "10 to 17",
        category: "Term 3",
    },
    {
        img: "/Prod-img3.jpg",
        title: "Networking and Data Security",
        //star: <AiFillStar className="rating-star" />,
        //reviews: "(123 reviews)",
        //prevPrice: "$140,00", 
        //newPrice: "$150",
        Age: "6 to 9",
        category: "Term 3",
    },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "Wedo Robotics L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Wedo Robotics L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "Stem L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Stem L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Genio Park", 
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "To the Rescue",  
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "The Zoo",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "6 to 9",
    //     category: "Wedo 2.0",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Math fun",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "6 to 9",
    //     category: "Lego kit",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "Video games Jr L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "6 to 9",
    //     category: "Kodu software",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Video games Jr L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "6 to 9",
    //     category: "Kodu software",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Video games Jr L3",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "6 to 9",
    //     category: "Kodu software",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "Video games Sr L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "6 to 9",
    //     category: "Scratch Software",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "Video games Sr L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "6 to 9",
    //     category: "Scratch Software",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Video games with Wedo 2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "6 to 9",
    //     category: "Scratch Software",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "Video games with Microbits",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "6 to 9",
    //     category: "Scratch Software",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Mechanics",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Electronics",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "Junior Rob.L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "Junior Rob.L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Junior Rob.L3",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$$150,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "Junior Robotics design",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Senior Robotics L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Senior Robotics L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "Senior Robotics L3",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Senior Robotics Design",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "Controlled Robotics",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "EV3 Robots",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "Arduino L1",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "10 to 17",
    //     category: "Arduino Kits",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "Arduino L2",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "Arduino Kits",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Arduino L3",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "Arduino Kits",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "HTML",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "10 to 17",
    //     category: "Web development",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "CSS",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "Web development",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "JavaScript",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "Web development",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "PHP",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "Web development",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "Mobile Application",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "Programming",
    // },
    // {
    //     img: "/Prod-img1.jpg",
    //     title: "Python",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$100",
    //     Age: "10 to 17",
    //     category: "Programming",
    // },
    // {
    //     img: "/Prod-img3.jpg",
    //     title: "Java",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "Programming",
    // },
    // {
    //     img: "/Prod-img4.jpg",
    //     title: "Advanced Robo Mechanics",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "Tetrix",
    // },
    // {
    //     img: "/Prod-img6.jpg",
    //     title: "FLL Preparation",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$50",
    //     Age: "10 to 17",
    //     category: "Competition training",
    // },
    // {
    //     img: "/Prod-img5.jpg",
    //     title: "FTC Preparation",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$150",
    //     Age: "10 to 17",
    //     category: "Competition training",
    // },
    // {
    //     img: "/Prod-img7.jpg",
    //     title: "FLL Advanced",
    //     star: <AiFillStar className="rating-star" />,
    //     reviews: "(123 reviews)",
    //     //prevPrice: "$140,00",
    //     newPrice: "$200",
    //     Age: "10 to 17",
    //     category: "Competition training",
    // },   
];

export default data;
